### PR TITLE
Added example heroku setup

### PR DESCRIPTION
**Pull request by SAGV**
@mhogerheijde as discussed today in the morning

### CODE REVIEW

**Comment by mhogerheijde** [comment]
But how to we include our configuration?

I'm looking for a 1 plan rules them all kind of thing, where - in case of mayham - I can find all information to recreate this setup.

E.g.
1. create account on Heroku
2. install npm (brew / apt-get install npm)
3. install nodejs
4. ????
5. profit!

**Comment by SAGV** [comment]
@mhogerheijde  Then I need to look on your config setup first ;-)

**Comment by mhogerheijde** [comment]
I meant eeh how to we tell heroku to use our server.js code?

**Comment by SAGV** [comment]
@mhogerheijde Procfile

**Comment by mhogerheijde** [comment]
Can you rebase?

**Pull request closed without merging**
